project:
  type: website
  output-dir: docs

website:
  title: "EC349"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Seminar 1
        menu: 
        - href: seminar-1.qmd
          text: Material
        - href: seminar-1-grp-1.qmd
          text: Group 1
        - href: seminar-1-grp-2.qmd
          text: Group 2
        - href: seminar-1-grp-3.qmd
          text: Group 3 
        - href: seminar-1-grp-4.qmd
          text: Group 4     
        - href: seminar-1-grp-5.qmd
          text: Group 5        
      - text: Seminar 2
        menu:
        - href: seminar-2.qmd
          text: Material
        - href: seminar-2-sol-1.qmd
          text: Solution 1
      - text: Seminar 3
        menu:
        - href: seminar-3.qmd
          text: Material
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

execute:
  freeze: auto   
